apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: applications
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/kse-youpiteron-api-security/kse-labs-deployment.git
        revision: main
        directories:
          - path: applications/*
  template:
    metadata:
      name: 'svc-{{path.basename}}'
    spec:
      project: applications
      source:
        repoURL: https://github.com/kse-youpiteron-api-security/kse-labs-deployment.git
        targetRevision: main
        path: '{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: applications
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        retry:
          limit: 10
          backoff:
            duration: 30s
            factor: 2
            maxDuration: 5m
        syncOptions:
          - CreateNamespace=true
