apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: infra
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/kse-youpiteron-api-security/kse-labs-deployment.git
        revision: main
        directories:
          - path: infra/*
  template:
    metadata:
      name: 'infra-{{path.basename}}'
      annotations:
        argocd.argoproj.io/sync-wave: "-1"
    spec:
      project: infra
      source:
        repoURL: https://github.com/kse-youpiteron-api-security/kse-labs-deployment.git
        targetRevision: main
        path: '{{path}}'
        directory:
          recurse: true
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{path.basename}}'
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        retry:
          limit: 10
          backoff:
            duration: 30s
            factor: 2
            maxDuration: 5m
        syncOptions:
          - CreateNamespace=true
